### PR TITLE
RetroArch

### PR DESCRIPTION
**Pull request by eudaldgr**
[RetroArch](https://www.retroarch.com/) & [Libretro](https://www.libretro.com/) with some cores, this not solves issue #47 but builds a `libretro-mame2000` & `libretro-mame2003`

### CODE REVIEW

**Comment by sdsddsd1** [comment]
Uh this is pretty nice!  
I am not quite sure to add it in its current form to the repo because there are so many packages. I think we need a restructure for this. I was against to divide the repo in directory sections because of easy maintenance, but maybe a subfolder games and one for retroarch? Or all the cores can be put in one package as they are mostly git versions? Suggestions welcome!

**Comment by eudaldgr** [comment]
Yes, I think a restructuring is necessary, but putting all the cores in a single package is counterproductive, you would be forced to install all without being able to choose which one you want and which not.

**Comment by sdsddsd1** [comment]
You are welcome to pullrequest again (:

**Comment by eudaldgr** [comment]
Done!

**Pull request merged**
