### PR TITLE
Openjazz

### PR DESCRIPTION
**Pull request by eudaldgr**
Best game ever!!
:tada: Finally comes to KISSLinux :tada:

### CODE REVIEW

**Comment by sdsddsd1** [comment]
This looks nice. I see you are a one of culture :D :+1:

**Comment by eudaldgr** [comment]
It's one of my plus beloved games of childhood, but i've problems with xmas dlc's. DOS Games are weird.

**Comment by sdsddsd1** [comment]
What do you mean? The christmas edition is freeware and easy to [find](https://gamesnostalgia.com/download/jazz-jackrabbit-holiday-hare-1994/1245?t=65203981).
Just use p7zip to extract the exe.
[Screenshot](https://u.teknik.io/6FT0R.png)

**Comment by eudaldgr** [comment]
There is two christmas edition `xmas94` and `xmas95` and the level filenames are equal.

**Pull request merged**
