### PR TITLE
emulationstation: new front-end at 2.9.3

### PR DESCRIPTION
**Pull request by eudaldgr**
# RetroPie [fork](https://github.com/RetroPie/EmulationStation) of EmulationStation.
A graphical and themeable emulator front-end that allows you to access all your favorite games in one place, even without a keyboard!

### CODE REVIEW

**Comment by sdsddsd1** [comment]
Ah nice, those frontends make retroarch complete (: .
But I dont like about it that it pulls in another another mediaplayer which therefore will need qt5(!!).
Is there away to change to mpv? Or even the choice for a lighter frontend?

**Comment by eudaldgr** [comment]
At this moment, this pkg don't build without `vlc`, I'll keep trying.

**Comment by sdsddsd1** [comment]
Ok, when emulationstation needs it, it needs it (: . I will then just merge it.
Have you tried building vlc with: 
```
--disable-qt
--disable-a52
```

**Comment by eudaldgr** [comment]
Well this is all I can do. Please check #67.
There is another [fork](https://gitlab.com/recalbox/recalbox-emulationstation) of `emulationstation` from recalbox , which makes use of `ffmpeg` instead of `vlc`, but I am not able to build it.

**Comment by eudaldgr** [comment]
There is something missing here to not merge this?

**Comment by sdsddsd1** [comment]
Have you seen my comments about the desktop file and the thumbnail?

**Comment by eudaldgr** [comment]
Where?

**Comment by sdsddsd1** [comment]
Ok, no clue why they are not visible to you. I asked to add `retroarch` to the depends file of emulation station. So when you build emulation station, retroarch gets automatically build. The second thing I asked, why the need of an desktop file and icon thumbnail. Because no other package provides them seberately and I would like to avoid this stuff because of kiss.

**Comment by sdsddsd1** [comment]
jibbieh.

**Pull request merged**
